# (c) 2010 The Board of Trustees of the University of Illinois.
LANGUAGE=c
SRCDIR_OBJS=main.o readatom.o output.o excl.o cutcpu.o
APP_LDFLAGS=-lm
APP_CFLAGS += -O2 -mavx2 -fopenmp-simd
#APP_CFLAGS += -S