# (c) 2007 The Board of Trustees of the University of Illinois.

LANGUAGE=c
SRCDIR_OBJS=main.o file.o
APP_CFLAGS=-ffast-math -O2 -mavx2 -fopenmp-simd
APP_CXXFLAGS=-ffast-math
APP_CXXFLAGS += -O2 -mavx2 -fopenmp-simd
APP_LDFLAGS=-lm -lstdc++
